python -m torch.distributed.launch --nproc_per_node 2 --master_port 9999 train.py \
  --sync-bn \
  --workers 4 \
  --device 0,1 \
  --batch 96 \
  --data datahub/small_coco/data.yaml \
  --img 640 \
  --cfg models/detect/yolov9-c-rtdetr.yaml \
  --weights 'weights/yolov9-c.pt' \
  --name "yolov9-c-rtdetr" \
  --hyp data/hyps/hyp.deyo.yaml \
  --epochs 300 \
  --close-mosaic 15 \
  --freeze 23 \
  --optimizer AdamW